### ISSUE TITLE
Fog.Local Directories.get(path, options) is not replicating same behavior as Fog.AWS.

### ISSUE THREAD

**Issue by mihairadulescu** [fog/fog-local#10]
The fact that we can switch from AWS to local storage is absolutely great.  For our integration tests that is simply perfect but there is an issue. The aws behaviour is different than local.
The local storage does not take prefix in account. Because of that if i just switch from aws to local, calls like get("bucket", {prefix: '/usa/states/') will not retrieve the folder in bucket/usa/states/, 
i would like to make a pr with this... i need to ask you guys first if that is desired by everyone or am i using this in an edge case ?

` def get(key, options = {})
          if ::File.directory?(service.path_to(key)) **#here is the issue .. we need to also take prefix into account when building paths.**
            new(:key => key)
          else
            nil
          end
        end
`

**Comment by lautis** [comment]
I'm not at least aware of any issues with the approach that you suggested. Using fog-local instead of fog-aws in some situations is perhaps the primary use case and as such it'd make sense to also support prefix option.

**Comment by plribeiro3000** [comment]
Agreed with @lautis.

since the signature you are proposing wont be `aws` specific, it would be even greater because other providers might use it as well. 

👍 from me!

**Comment by mihairadulescu** [comment]
https://github.com/fog/fog-local/pull/11 i have a pr for the prefix usage. my tests are passing when changing from aws to local... in a single point of change.

**Comment by plribeiro3000** [comment]
Closing this in favor of #11 so we can keep the conversation centralized there. 
👍  for the initiative!
