### ISSUE TITLE
New version on rubygems

### ISSUE THREAD

**Issue by brancz** [fog/fog-local#9]
Hey there. I recently posted #8 and it was merged a couple hours ago. Do you think we could push a new version to rubygems? I would be glad to help and do it myself if I get access granted.

Thank you for taking your time for this. Much appreciated. :grin:

**Comment by plribeiro3000** [comment]
Sure. will do in a bit.

**Comment by plribeiro3000** [comment]
Done. It is out as `0.3.0`.

**Comment by brancz** [comment]
Thank you so much for your time. Hugely appreciated! :+1:
